fail_fast: true  # pre-commit will stop running hooks after the first failure.
default_stages: [ commit, push ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black
        entry: black
        types: [ python ]
        args: [ --line-length=100 ]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --ignore-init-module-imports ]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1  # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        files: th2_data_services
        args:
          - --convention=google
          - --add-ignore=D100,D101,D104,D105,D403,  D102,   # http://www.pydocstyle.org/en/stable/error_codes.html