name: CI tests

on:
  push:

jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        py_version: [ '3.8', '3.9', '3.10' ]
        os: [ ubuntu-20.04, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install --pre -e . -q  # Install current lib version
          pip install pytest
          pip install pytest-xdist

      - name: lwdp unit tests
        run: |
          pip list
          pytest tests/tests_unit -n auto